library("ReactomePA")
#looks at pathway enrichment from clusters generated by Cfinder

convert = function(gene.list,id.map){

entrez.list = id.map[which(id.map[,1] %in% gene.list),2]

}

id.map = read.delim("Entrez-ids.txt")
id.map = id.map[which(id.map$Species == "Homo sapiens"),]

clique = read.delim("clique-file.tsv")
comm = read.delim("commun-file.tsv")

cliques = unique(clique[,1])
clique.enrich.list = list()

for(c in cliques){

	gene.clique = clique[which(clique[,1] ==c),2] 
	if(length(gene.clique) < 10){
		next	
	}
	entrez.clique =convert(gene.clique,id.map)
	x = enrichPathway(as.character(entrez.clique),pvalueCutoff=0.05, readable=T)
	if(is.null(x)){
		next
	}	
	pdf(paste("img2/clique-plots/plot-clique-",c,"-",length(gene.clique),".pdf",sep =""),width = 15,height = 8)
	if(length(x$ID )<5){
		g= barplot(x,main = paste("clique size =",as.character(length(gene.clique))))
		print(g)
		dev.off()
		}else{
		g  =barplot(x,showCategory=5,main = paste("clique size =",as.character(length(gene.clique))))
		print(g)
		dev.off()}
	
	clique.enrich.list[[as.character(c)]] = x 
	print(c)
	print("/")
	print(length(cliques)-1)

}

save(clique.enrich.list,file  ="clique-enrich-list.Rdata")

community.enrich = list()

ks = unique(comm[,2])
for(k in ks){
	k = as.character(k)
	community.enrich[[k]] =list()
	comm.sub = comm[which(comm[,2] ==k),]
	communities = unique(comm.sub[,1])
	if(length(communities) == 1){
		next
	}
	for(community in communities){

		gene.community = comm.sub[which(comm.sub[,1] ==community),3]
		entrez.community = convert(gene.community,id.map)
		x = enrichPathway(entrez.community,pvalueCutoff=0.05, readable=T)
		pdf(paste("img2/community-plots/",k,"-",community,"-",length(gene.community),".pdf",sep =""))
    		if(length(x$ID )<5){
			g= barplot(x,main = paste("clique size =",as.character(length(communities))))
			print(g)
			dev.off()
		}else{
			g  =barplot(x,showCategory=5,main = paste("community size =",as.character(length(communities))))
			print(g)
			dev.off()}
		community.enrich[[k]][[as.character(community)]] = x

	}

}

save(community.enrich,file = "community-enrich.Rdata") 
